### PR TITLE
Updated attack map using generate_attack_map.py

### PR DESCRIPTION
**Pull request by cccs-kevin**
Updating the attack map , and by the looks of it, several ATT&CK IDs do not exist anymore (T1086, T1060, T1063, T1188, T1158, T1089, T1103, T1045, etc.), and could break services (Cuckoo) if these are included in the service_manifest.yml files under heuristic declaration.

### CODE REVIEW

**Review by cccs-rs — APPROVED** [review]
👍

**Review by cccs-rs — APPROVED** [review]
LGTM 👍

**Comment by cccs-kevin** [comment]
@adam-douglass @cccs-sgaron Can you review this PR please and let me know if it is good to merge?

**Review by cccs-sgaron — COMMENTED** [review]
We should probably add test that test the different features of the Attack Map like mapping a software family to multiple attack IDs and getting the pattern name and category of a couple attack IDs... That way updating the map would be safer. Otherwise this is a bit rough looking through 14K added and 7K removed lines.

**Review by cccs-sgaron — APPROVED** [review]

**Pull request merged**
